import 'reflect-metadata'
import { X509Certificate } from '@peculiar/x509'

export const issuerCertificate = new X509Certificate(`-----BEGIN CERTIFICATE-----
MIIBQTCB76ADAgECAiBtxZMzkeRG1H7HmLdQGvZQTeY3NmAVroE8U1glBaBFQzAK
BggqhkjOPQQDAjAeMQ8wDQYDVQQDDAZJc3N1ZXIxCzAJBgNVBAYTAkNIMB4XDTI1
MDEzMDEwNTYwNFoXDTI2MDEzMDEwNTYwNFowHzELMAkGA1UEBhMCQ0gxEDAOBgNV
BAMMB1N1YmplY3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ2sWdrE5B3m+Xv
09wUBShYmf4V1Rs44oJlotAN2fZKZ86AmgyRYKc1wDYyCFBSVQIDOTh1cvSC2aKk
tb9aRVFMMAoGCCqGSM49BAMCA0EAcgjH/q6Sl4xjuAK3F+1ZxJjZT5iZzcILfFaj
ndzUGIEt+r+NKUBudbinH5yO3/QhRCCZLuhOoOQPsmilkUjqmg==
-----END CERTIFICATE-----`)
