/**
 * Regenerates `src/eu-lotl-anchors.ts` — the EU List of Trusted Lists (LOTL)
 * signing certificates shipped with this package as the default trust anchors.
 * Run from the package directory:
 *
 *   pnpm exec tsx scripts/refresh-lotl-anchors.mts
 *   pnpm exec tsx scripts/refresh-lotl-anchors.mts --bootstrap
 *
 * The LOTL is fetched live, its signature is verified against the currently
 * shipped anchors (so a rotation is only picked up through a list signed by the
 * previous generation of keys), and the new set is read from the LOTL's own
 * `EU` self-pointer. `--bootstrap` skips the pin check and is only for the very
 * first run or to recover from a fully expired set — in that case the printed
 * fingerprints MUST be cross-checked against the Official Journal publication
 * before the result is committed.
 *
 * After regenerating, run `pnpm style:fix` at the repo root. Whatever this
 * script writes is a trust anchor: review the diff.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { base64, hexEncode } from '@owf/identity-common'
import * as x509 from '@peculiar/x509'
import { TSLType } from '../src/constants'
import { getPointerSigningCertificates, parseTrustedList } from '../src/parse'
import { verifyTrustedListSignature } from '../src/verify'

const LOTL_URL = 'https://ec.europa.eu/tools/lotl/eu-lotl.xml'
const bootstrap = process.argv.includes('--bootstrap')

const response = await fetch(LOTL_URL)
if (!response.ok) throw new Error(`Could not fetch the LOTL: ${response.status} ${response.statusText}`)
const xml = await response.text()

let pinned: Uint8Array[] = []
try {
  const current = await import('../src/eu-lotl-anchors')
  pinned = current.EU_LOTL_SIGNING_CERTIFICATES.map((entry) => base64.decode(entry.certificate))
} catch {
  // No anchors shipped yet — only valid together with --bootstrap.
}
if (pinned.length === 0 && !bootstrap) {
  throw new Error('No anchors are currently shipped; re-run with --bootstrap and verify against the Official Journal')
}

await verifyTrustedListSignature(xml, bootstrap ? {} : { trustAnchors: pinned })
console.log(
  bootstrap ? 'Signature is cryptographically valid (NOT pinned)' : 'Signature verified against shipped anchors'
)

const lotl = parseTrustedList(xml)
const certificates = getPointerSigningCertificates(lotl, { tslType: TSLType.EUlistofthelists })
if (certificates.length === 0) throw new Error('The LOTL self-pointer carries no signing certificates')

const officialJournal = xml.match(/https:\/\/eur-lex\.europa\.eu\/eli\/[^<\s]+/)?.[0]
if (!officialJournal) throw new Error('No Official Journal (ELI) reference found in the LOTL')

const described = await Promise.all(
  certificates.map(async (der) => {
    const certificateBase64 = base64.encode(der)
    const certificate = new x509.X509Certificate(certificateBase64)
    return {
      certificate: certificateBase64,
      subject: certificate.subject,
      fingerprintSha256: hexEncode(new Uint8Array(await crypto.subtle.digest('SHA-256', der as BufferSource))),
      notAfter: certificate.notAfter.toISOString(),
    }
  })
)
described.sort((a, b) => a.fingerprintSha256.localeCompare(b.fingerprintSha256))

console.log(
  `\n${described.length} signing certificates published by the LOTL (cross-check against ${officialJournal}):`
)
for (const entry of described) {
  console.log(`  ${entry.fingerprintSha256}  notAfter=${entry.notAfter.slice(0, 10)}  ${entry.subject}`)
}

const earliestNotAfter = described.map((entry) => entry.notAfter).sort()[0]
const file = `/**
 * EU List of Trusted Lists (LOTL) signing certificates — GENERATED by
 * \`scripts/refresh-lotl-anchors.mts\`, do not edit by hand.
 *
 * These are the certificates the European Commission publishes as the signers
 * of the LOTL. They are the out-of-band trust anchor of the whole eIDAS trusted
 * list hierarchy: the set cannot be derived from the LOTL alone (a forged list
 * would carry a forged self-pointer), so it is pinned here and cross-checked
 * against the Official Journal publication referenced below.
 *
 * Source list: ${LOTL_URL}
 * Official Journal: ${officialJournal}
 */

/** One certificate the European Commission publishes as a LOTL signer. */
export interface EuLotlSigningCertificate {
  /** base64-encoded DER. */
  certificate: string
  /** Subject distinguished name, for human review of the pinned set. */
  subject: string
  /** Lowercase-hex SHA-256 of the DER, for out-of-band cross-checking. */
  fingerprintSha256: string
  /** Certificate expiry (ISO 8601). */
  notAfter: string
}

/**
 * The signing certificates published by the LOTL identified in
 * {@link EU_LOTL_ANCHORS_PROVENANCE}. Any of them may sign a future issue of the
 * list, so the whole published set is pinned, not just the current signer.
 */
export const EU_LOTL_SIGNING_CERTIFICATES: readonly EuLotlSigningCertificate[] = ${JSON.stringify(described, null, 2)}

/** Where this set came from, so the pin can be audited without re-running the script. */
export const EU_LOTL_ANCHORS_PROVENANCE = {
  /** The list the certificates were read from. */
  source: '${LOTL_URL}',
  /** The Official Journal act the LOTL itself references for its signers. */
  officialJournal: '${officialJournal}',
  /** \`TSLSequenceNumber\` of that list. */
  tslSequenceNumber: ${lotl.sequenceNumber ?? 'undefined'},
  /** \`ListIssueDateTime\` of that list. */
  listIssueDateTime: '${lotl.listIssueDateTime ?? ''}',
  /** Earliest expiry in the set: refresh before this date. */
  earliestNotAfter: '${earliestNotAfter}',
} as const
`

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'eu-lotl-anchors.ts')
writeFileSync(outPath, file)
console.log(`\nWrote ${outPath} (sequence ${lotl.sequenceNumber}, earliest notAfter ${earliestNotAfter.slice(0, 10)})`)
