/**
 * Test fixtures generated with OpenSSL 3.6, independently of this package.
 * The CA key is a throwaway test key.
 */

/** Issuing CA: C=DE, O=Example Access CA Provider, organizationIdentifier=NTRDE-HRB12345, CN=Example WRP Access CA */
export const CA_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIICCTCCAbCgAwIBAgIBATAKBggqhkjOPQQDAjBrMQswCQYDVQQGEwJERTEjMCEG
A1UECgwaRXhhbXBsZSBBY2Nlc3MgQ0EgUHJvdmlkZXIxFzAVBgNVBGEMDk5UUkRF
LUhSQjEyMzQ1MR4wHAYDVQQDDBVFeGFtcGxlIFdSUCBBY2Nlc3MgQ0EwHhcNMjYw
OTI4MTk1OTA2WhcNMzYwOTI1MTk1OTA2WjBrMQswCQYDVQQGEwJERTEjMCEGA1UE
CgwaRXhhbXBsZSBBY2Nlc3MgQ0EgUHJvdmlkZXIxFzAVBgNVBGEMDk5UUkRFLUhS
QjEyMzQ1MR4wHAYDVQQDDBVFeGFtcGxlIFdSUCBBY2Nlc3MgQ0EwWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAARg0c8sALBbzE/SFVqttq8OdUmAewJixq8yhU8EXhbb
9sxiRnhAQg5ymI7lvJAFxx15QMhFCCIPhfS2LpY39Ihxo0UwQzASBgNVHRMBAf8E
CDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUdd0cs56P7zfHv4eI
vh+sGm/XPfkwCgYIKoZIzj0EAwIDRwAwRAIgYkMrTbHkFQVYaIpdmbn+Gw5KjFH8
7Nd8vbZoZNwMFiYCIBS/aia34bqtP/3GeUgtuDoE7qHHRo8Wr/Woma9EBFB1
-----END CERTIFICATE-----
`

export const CA_PRIVATE_JWK = {
  kty: 'EC',
  crv: 'P-256',
  x: 'YNHPLACwW8xP0hVarbavDnVJgHsCYsavMoVPBF4W2_Y',
  y: 'zGJGeEBCDnKYjuW8kAXHHXlAyEUIIg-F9LYuljf0iHE',
  d: 'KaBuJCiaRG4HO8IXQPAZI9nDFhYT2fz_4P-sNYKSnFA',
}

/** End-entity certificate (serial 0badc0de) issued by the CA above, valid 2026-09-28 until 2036-09-25 */
export const OPENSSL_LEAF_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIDpjCCA0ygAwIBAgIEC63A3jAKBggqhkjOPQQDAjBrMQswCQYDVQQGEwJERTEj
MCEGA1UECgwaRXhhbXBsZSBBY2Nlc3MgQ0EgUHJvdmlkZXIxFzAVBgNVBGEMDk5U
UkRFLUhSQjEyMzQ1MR4wHAYDVQQDDBVFeGFtcGxlIFdSUCBBY2Nlc3MgQ0EwHhcN
MjYwOTI4MTk1OTA2WhcNMzYwOTI1MTk1OTA2WjB5MQswCQYDVQQGEwJERTEjMCEG
A1UECgwaRXhhbXBsZSBSZWx5aW5nIFBhcnR5IEdtYkgxFDASBgNVBAsMC09ubGlu
ZSBTaG9wMRgwFgYDVQRhDA9WQVRERS0xMjM0NTY3ODkxFTATBgNVBAMMDEV4YW1w
bGUgU2hvcDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHMcGZ3HO/exk+1jjOll
Vt1KKAGwP5BcBs+KYVDjvw/awTaQAQhU5fi13yMznVkbuI7+5c16r+w0LI7t1FYg
MsqjggHOMIIByjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4E
FgQUbZvDzbe2oVZqqcG3xfbbu0GAk78wHwYDVR0jBBgwFoAUdd0cs56P7zfHv4eI
vh+sGm/XPfkwPgYDVR0gBDcwNTAzBgcEAIvsRgEEMCgwJgYIKwYBBQUHAgEWGmh0
dHBzOi8vY2EuZXhhbXBsZS5jb20vY3BzMG0GA1UdEQRmMGSCEHNob3AuZXhhbXBs
ZS5jb22GIGh0dHBzOi8vc2hvcC5leGFtcGxlLmNvbS9zdXBwb3J0gRhzdXBwb3J0
QHNob3AuZXhhbXBsZS5jb22gFAYDVQQUoA0TCys0OTMwMTIzNDU2MCsGA1UdHwQk
MCIwIKAeoByGGmh0dHBzOi8vY2EuZXhhbXBsZS5jb20vY3JsMF8GCCsGAQUFBwEB
BFMwUTAkBggrBgEFBQcwAYYYaHR0cHM6Ly9vY3NwLmV4YW1wbGUuY29tMCkGCCsG
AQUFBzAChh1odHRwczovL2NhLmV4YW1wbGUuY29tL2NhLmNydDAtBggrBgEFBQcB
AwQhMB8wCAYGBACORgEBMBMGBgQAjkYBBjAJBgcEAI5GAQYCMAoGCCqGSM49BAMC
A0gAMEUCIQCTOehzjd269zf3H1jEUgZdrM0cML+6H5d+3lsZf+OzOQIgNsvEnenR
i4IvgvE6YqyuxczNUeACbq4MVpqDYf3oCPg=
-----END CERTIFICATE-----
`

/**
 * CRL of the CA above (CRL number 4096, next update 2026-10-28T20:26:27Z), revoking the leaf
 * certificate with reason keyCompromise and invalidity date 2026-09-15T12:00:00Z. Its issuing
 * distribution point is https://ca.example.com/crl and it only covers end-entity certificates.
 */
export const OPENSSL_CRL_PEM = `-----BEGIN X509 CRL-----
MIIBmDCCAT4CAQEwCgYIKoZIzj0EAwIwazELMAkGA1UEBhMCREUxIzAhBgNVBAoM
GkV4YW1wbGUgQWNjZXNzIENBIFByb3ZpZGVyMRcwFQYDVQRhDA5OVFJERS1IUkIx
MjM0NTEeMBwGA1UEAwwVRXhhbXBsZSBXUlAgQWNjZXNzIENBFw0yNjA5MjgyMDI2
MjdaFw0yNjEwMjgyMDI2MjdaMD8wPQIEC63A3hcNMjYwOTI4MjAyNjI3WjAmMAoG
A1UdFQQDCgEBMBgGA1UdGAQRGA8yMDI2MDkxNTEyMDAwMFqgYTBfMB8GA1UdIwQY
MBaAFHXdHLOej+83x7+HiL4frBpv1z35MC8GA1UdHAEB/wQlMCOgHqAchhpodHRw
czovL2NhLmV4YW1wbGUuY29tL2NybIEB/zALBgNVHRQEBAICEAAwCgYIKoZIzj0E
AwIDSAAwRQIhAI7guhz+Hzb98MIJfnZvIS+T+S46WZWDTKYqJfXzyp/LAiAhJiMu
s7NHO/ruI1efoTg40DuREk5frGmsoZwZ+NyGCg==
-----END X509 CRL-----
`
